version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - '54322:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: